services:
  guiniverse2:
    image: guiniverse2:dev
    build:
      context: .
    network_mode: host
    stop_signal: SIGINT
    privileged: true

    environment:
      CYCLONEDDS_URI: >
        <CycloneDDS xmlns="https://cdds.io/config">
          <Domain>
            <General>
              <Interfaces>
                <NetworkInterface name="enx68da73a18af6"/>
              </Interfaces>
            </General>
          </Domain>
        </CycloneDDS>
      SIM_MODE: ${SIM_MODE}
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      XAUTHORITY: ${XAUTHORITY}
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: "187"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./guiniverse2_data:/guiniverse2_data
      - ./guiniverse2_launch:/ros2_ws/src/guiniverse2_launch:ro
      - ${XAUTHORITY}:${XAUTHORITY}

    devices:
      - /dev/dri:/dev/dri

    command: >
      bash -c "
        set -e

        source /opt/ros/humble/setup.bash

        colcon build --packages-select guiniverse2_launch

        source /ros2_ws/install/setup.bash

        export VIDEO_TARGET_IP=$(ip -4 addr show enx68da73a18af6 | awk '/inet / {print $2}' | cut -d/ -f1)

        cd /guiniverse2_data

        ros2 launch guiniverse2_launch gui.launch.py sim_mode:=${SIM_MODE:-false}
      "